In [5]:
import numpy as np

In [6]:
list = [1,2,3,6,4]


In [7]:
type(list)

list

In [ ]:
#converting list into array
arr =np.array([list])

In [10]:
print(arr)


[[1 2 3 6 4]]


In [ ]:
# printing array for particular range 
arr=np.arange(1,10)

In [14]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# creating array of 2d array
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones(10)   # array of 1d 
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# creating aaray for particular range with 5 element and equal space
arr= np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
arr=np.arange(0,30)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#reshaping array of 1d into 2d (10*3)
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [24]:
arr.shape


(30,)

In [27]:
arr=np.random.randint(1,5,9)
arr

array([2, 2, 4, 2, 4, 1, 3, 1, 1])

In [ ]:
#reshaping a array in 2d array
arr=np.random.randint(1,5,(3,3))
arr


array([[4, 4, 2],
       [1, 3, 1],
       [2, 4, 3]])

In [ ]:
arr=np.random.random(10 )

In [31]:
arr

array([0.49214026, 0.6158574 , 0.5836931 , 0.89803936, 0.89704492,
       0.36508199, 0.39617085, 0.72797165, 0.34808834, 0.10079677])

In [32]:
arr=np.random.random((3,3))
arr

array([[0.00336342, 0.61020645, 0.69904375],
       [0.04033094, 0.03582466, 0.76356367],
       [0.85713407, 0.98564817, 0.70589924]])

In [ ]:
#finding the shape of array 
arr.shape

(3, 3)

In [ ]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [69]:
arr=arr.reshape((12,5))

In [ ]:
arr.dtype  # finding datatype of array

dtype('int32')

In [ ]:
arr.size  # finding size of array

60

In [ ]:
arr.ndim  # finding dimension of array

2

In [ ]:
# converting 2d array into 1d by ravel and flatten
# arr=arr.flatten()

In [74]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [75]:
arr.ndim

2

In [ ]:
# converting 2d array into 1d by ravel and flatten
arr.ravel().ndim

1

In [88]:
list_2d=[[1,2,3,4],[5,6,4,5],[5,6,5,4]]

In [89]:
arr=np.array(list_2d)

In [90]:
arr

array([[1, 2, 3, 4],
       [5, 6, 4, 5],
       [5, 6, 5, 4]])

In [91]:
arr.ndim

2

In [92]:
arr.shape

(3, 4)

In [95]:
arr=arr.T

In [96]:
arr

array([[1, 5, 5],
       [2, 6, 6],
       [3, 4, 5],
       [4, 5, 4]])

In [97]:
arr.shape

(4, 3)

In [98]:
arr=np.arange(60)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [101]:
arr[2]

2

In [103]:
arr[2:11]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [115]:
arr[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [120]:
arr=arr.reshape(60)

In [121]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [130]:
arr=arr.reshape(12,5)

In [132]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [133]:
arr[1]

array([5, 6, 7, 8, 9])

In [134]:
arr[0]

array([0, 1, 2, 3, 4])

In [135]:
arr[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [136]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [ ]:
# for finding the last element of array

# arr[11,4]
# arr[11][-1]
arr[-1][-1]

59

In [142]:
arr[:4][-1]

array([15, 16, 17, 18, 19])

In [143]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
# for replacing the element in array
arr[4,2]=100

In [146]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 100,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [147]:
arr=np.arange(225)

In [148]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [149]:
arr=arr.reshape(5,15,3)

In [150]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [151]:
arr.shape

(5, 15, 3)

In [152]:
arr.ndim

3

In [153]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [154]:
arr[0][2:]



array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [ ]:
arr[0][2:7]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [157]:
arr[0][2:7][0]

array([6, 7, 8])

In [158]:
arr[:,0:1,0:1]


array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [ ]:
arr[2][3][1]=500  # for replacing the element

In [160]:
arr[2][3][1]

500

In [161]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 500, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [162]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 500, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [163]:
arr=np.arange(60)

In [164]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [168]:
arr.reshape(12,5)




array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [169]:
arr *2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118])

In [170]:
arr -1


array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58])

In [171]:
arr=arr.reshape(12,5)

In [172]:
arr1=np.arange(60)

In [173]:
arr1=arr1.reshape(12,5)

In [174]:
arr + arr1

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118]])

In [192]:
x=[45,56,89,56]
y=[54,23,64,2]

In [193]:
x+y

[45, 56, 89, 56, 54, 23, 64, 2]

In [194]:
x*y

TypeError: can't multiply sequence by non-int of type 'list'

In [195]:
x=np.array(x)
y=np.array(y)

In [190]:
x+y

array([ 99,  79, 153,  58])

In [196]:
x*y

array([2430, 1288, 5696,  112])

In [17]:
from itertools import permutations, cycle,repeat, count


a=[1,2,3]
per = permutations(a)
print(per)